---
networks:
  eos:
    name: "eos"
services:
  eos:
    image: "akkudoktor/eos:${EOS_VERSION}"
    read_only: true
    build:
      context: .
      dockerfile: "Dockerfile"
      args:
        PYTHON_VERSION: "${PYTHON_VERSION}"
    init: true
    environment:
      FLASK_RUN_PORT: "${EOS_PORT}"
    networks:
      - "eos"
    volumes:
      - ./src/akkudoktoreos/default.config.json:/opt/eos/EOS.config.json:ro
    ports:
      - "${EOS_PORT}:${EOS_PORT}"
  docs:
    image: squidfunk/mkdocs-material:9
    restart: always
    networks:
      - eos
    volumes:
      - ./mkdocs.yaml:/docs/mkdocs.yaml:ro
      - ./docs:/docs/docs:ro
    ports:
      - "8000:8000"
